language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - jruby
  - rbx
gemfile:
  - Gemfile
  - Gemfile-pure
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
